In [4]:
import numpy as np                  

In [ ]:
# ZC - PCT

# Creating array of even integers from 30 to 70

In [5]:
# Create an array of even integers from 30 to 70
even_numbers = np.arange(30, 71, 2)

# np.arange(30, 71, 2) creates an array starting from 30, up to (but not including) 71, with a step size of 2. 
# This results in an array containing all even integers between 30 and 70.

# Print the array
print("Array of even integers from 30 to 70:", even_numbers)


Array of even integers from 30 to 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


# Generating an array of 15 random numbers (standard normal distribution)

In [6]:
# Generate an array of 15 random numbers from a standard normal distribution
random_numbers = np.random.randn(15)

# np.random.randn(15) generates an array of 15 random numbers from a standard normal distribution.

# Print the array
print("Array of 15 random numbers from a standard normal distribution:", random_numbers)


Array of 15 random numbers from a standard normal distribution: [ 1.2509873  -2.30968847 -0.02187199 -0.06050511  0.83974982 -0.37732744
 -1.05755145  0.48295545 -0.40307101  1.53506208 -1.12676935  1.86980256
 -0.37545011 -1.42522858  0.0872171 ]


# Cross-product of two matrices

In [7]:
# Create two matrices (2D arrays)
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

# Compute the cross-product
cross_product = np.cross(matrix1, matrix2)

# Print the result
print("Cross-product of the two matrices:")
print(cross_product)

# In NumPy, you can compute the cross-product of two matrices using the np.cross() function. 
# The np.cross() function calculates the cross-product of two arrays along a specified axis.
# If the input arrays are 2-D, it computes the cross-product of corresponding rows.


Cross-product of the two matrices:
[[-10  20 -10]
 [-10  20 -10]
 [-10  20 -10]]


## Element-wise product of two matrices

In [8]:
# You can use the * operator for element-wise multiplication, 
# but keep in mind that the * operator in NumPy performs element-wise multiplication, 
# not the cross product in the traditional sense.

# Create two matrices (2D arrays)
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

# Compute the element-wise cross-product using the * operator
elementwise_cross_product = matrix1 * matrix2#

# Print the result
print("Element-wise cross-product of the two matrices:")
print(elementwise_cross_product)


# In this example, matrix1 * matrix2 performs element-wise multiplication. 
# This is not the same as the cross product, but it's a common operation when 
# people refer to an "element-wise cross-product" for matrices.

# If you specifically need the traditional cross product (not element-wise), 
# you should use np.cross() as shown in the previous example.

Element-wise cross-product of the two matrices:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


# Computing the determinant of an array

In [9]:
# In NumPy, you can compute the determinant of a square matrix using the numpy.linalg.det() function


# Create a square matrix
matrix = np.array([[4, 7],
                   [2, 6]])

# Compute the determinant
determinant_value = np.linalg.det(matrix)

# Print the determinant
print("Determinant of the matrix:")
print(determinant_value)


# matrix is a 2x2 square matrix, and np.linalg.det(matrix) calculates its determinant.
# The input matrix must be a square matrix (number of rows equals the number of columns) for 
# the determinant to be defined. 
# If the matrix is not square, the function will raise a LinAlgError.


Determinant of the matrix:
10.000000000000002


##  Determinant of different sized square matrices

In [10]:
# Deinfining some square arrays
array_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Compute determinants
det_3x3 = np.linalg.det(array_3x3)
det_4x4 = np.linalg.det(array_4x4)

# Display results
print(f"Determinant of 3x3 array:\n{det_3x3}")
print(f"Determinant of 4x4 array:\n{det_4x4}")


Determinant of 3x3 array:
-9.51619735392994e-16
Determinant of 4x4 array:
-1.820448242817726e-31


# Creating a 3x3x3 array with random values (uniform distribution 0-1)

In [11]:
# You can create a 3x3x3 array with random values in NumPy using the numpy.random.rand function, 
# which generates random values from a uniform distribution between 0 and 1. 


# Create a 3x3x3 array with random values
random_3_array = np.random.rand(3, 3, 3)

# Print the array
print("3x3x3 Array with Random Values:")
print(random_3_array)


3x3x3 Array with Random Values:
[[[0.90957894 0.199463   0.52758389]
  [0.54220517 0.38895335 0.11838558]
  [0.86990654 0.49825611 0.11441816]]

 [[0.10129979 0.58357634 0.32852561]
  [0.76898153 0.32364687 0.03175303]
  [0.92552969 0.14401398 0.95073715]]

 [[0.23849809 0.92879013 0.19363852]
  [0.57127897 0.50682192 0.9284751 ]
  [0.77099543 0.0802393  0.05712819]]]


## Creating a 3x3x3 array of random values (standard normal distribution)

In [12]:
# If you want random values from a different distribution, you can use other functions from the numpy.random module. 
# For example, numpy.random.randn generates random values from a standard normal distribution:


# Create a 3x3x3 array with random values from a standard normal distribution
random_array_normal = np.random.randn(3, 3, 3)

# Print the array
print("3x3x3 Array with Random Values (Standard Normal Distribution):")
print(random_array_normal)



3x3x3 Array with Random Values (Standard Normal Distribution):
[[[-0.45574831 -1.85705837  0.35911362]
  [ 0.25199552 -1.24443469  0.07654536]
  [ 0.08363315 -0.44097306  1.9477491 ]]

 [[-0.32447859  1.28025047  0.18519213]
  [ 0.17125735 -0.32961591  0.53846073]
  [ 0.57099707 -0.63920028 -0.23886121]]

 [[-0.47527997 -0.327629    1.02245541]
  [ 0.63577097  0.87184879  0.33348397]
  [-0.43455222 -0.68201204  0.02808309]]]


# Creating a 5x5 array and finding min. and max. values

In [13]:
# You can create a 5x5 array with random values and find the minimum and maximum values using NumPy's functions


# Create a 5x5 array with random values
random_5_array = np.random.rand(5, 5)

# Print the array
print("5x5 Array with Random Values:")
print(random_5_array)

# Find the minimum and maximum values
min_value = np.min(random_5_array)
max_value = np.max(random_5_array)

# Print the minimum and maximum values
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)


# np.random.rand(5, 5) generates a 5x5 array with random values from a uniform distribution in the range [0, 1).
# np.min(random_array) finds the minimum value in the array.
# np.max(random_array) finds the maximum value in the array.


5x5 Array with Random Values:
[[0.04702647 0.88970897 0.70912698 0.10693256 0.82015244]
 [0.79142396 0.22570596 0.36002554 0.60911244 0.36498738]
 [0.03622169 0.65886303 0.13321998 0.74585385 0.59689376]
 [0.05766458 0.73755818 0.58531944 0.72579311 0.59967098]
 [0.70029689 0.47657903 0.88246342 0.57400367 0.29313915]]
Minimum Value: 0.03622169342161563
Maximum Value: 0.8897089721124494


# Computing mean, std dvtn & var. along second axis of an array

In [14]:
# In NumPy, you can compute the mean, standard deviation, and variance along a specific axis of an array 
# using the functions numpy.mean(), numpy.std(), and numpy.var(). Here's an example of calculating these 
# statistics along the second axis (axis=1):
# The axis=1 argument is used to perform the calculations along the second axis.
# axis=0: Operations along the vertical axis (down the rows).
# axis=1: Operations along the horizontal axis (across the columns).
# Adjust the axis parameter based on your data structure and the axis along which you want to compute these statistics.



# Create a sample 3x4 array
data_array = np.array([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12]])

# Compute mean along the second axis (axis=1)
mean_values = np.mean(data_array, axis=1)

# Compute standard deviation along the second axis (axis=1)
std_deviation_values = np.std(data_array, axis=1)

# Compute variance along the second axis (axis=1)
variance_values = np.var(data_array, axis=1)

# Print the results
print("Original Array:")
print(data_array)

print("\nMean along the second axis:")
print(mean_values)

print("\nStandard Deviation along the second axis:")
print(std_deviation_values)

print("\nVariance along the second axis:")
print(variance_values)



Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Mean along the second axis:
[ 2.5  6.5 10.5]

Standard Deviation along the second axis:
[1.11803399 1.11803399 1.11803399]

Variance along the second axis:
[1.25 1.25 1.25]
